### ISSUE TITLE
run fuzzers with -jobs (or -workers?) for parallelism

### ISSUE THREAD

**Issue by alex** [google/clusterfuzzlite#105]
github actions provides two cores, but clusterfuzzlite only uses 1. passing `-j $(ncpu)` gets free extra capacity :-)

**Comment by jonathanmetzman** [comment]
Yeah we definitely should do this. I didn't out of caution for stability purposes, but it is worth a try.

**Comment by alex** [comment]
If you throw it behind an experimental option or something that's fine by me :-)

**Comment by jonathanmetzman** [comment]
Sorry I'll land this on Monday

**Comment by securitykernel** [comment]
Nice addition, thanks! Shouldn't this be added to the docs, too?

**Comment by jonathanmetzman** [comment]
> Nice addition, thanks! Shouldn't this be added to the docs, too?

Yup. I'll try to get around to this tonight
