### ISSUE TITLE
Exclude files from coverage

### ISSUE THREAD

**Issue by szhorvat** [google/clusterfuzzlite#135]
On OSS-fuzz, we use `coverage_extra_args: -ignore-filename-regex=...` in `project.yaml` to exclude some files from the coverage reports. This does not seem to work with ClusterFuzzLite and CIFuzz.

Does ClusterFuzzLite provide any way to exclude some files from the coverage reports?

**Comment by jonathanmetzman** [comment]
What are you seeing that makes you think this is not respected in CIFuzz?
Also, to clarify, you are using ClusterFuzzLite to generate coverage reports?
Or do you mean for determining which fuzzer to use.

**Comment by szhorvat** [comment]
I am new to ClusterFuzzLite, and only set up the integration yesterday (while we've been using OSS-Fuzz for a couple of years now). Perhaps I did something wrong.

These are our projects configurations:

 - ClusterFuzzLite: https://github.com/igraph/igraph/tree/master/.clusterfuzzlite
 - OSS-Fuzz: https://github.com/google/oss-fuzz/tree/master/projects/igraph

They have the same exclusion rules. But the values I see in the ClusterFuzzLite report don't seem to respect the exclusions:

https://igraph.github.io/clusterfuzz-storage-repo/coverage/latest/report/linux/report.html

In comparison, line coverage reported by OSS-Fuzz is 58%.

These are our GitHub Actions workflows (just set up yesterday): https://github.com/igraph/igraph/tree/master/.github/workflows  I ran [cflite_cron.yml](https://github.com/igraph/igraph/blob/master/.github/workflows/cflite_cron.yml) manually just a few minutes ago, hoping that it'd update coverage reports based on the newly added exclusion rules. And it did indeed [push an update](https://github.com/igraph/clusterfuzz-storage-repo/commit/01efd8bd2052a9223a569da0de08279f51872bee#diff-3812aad2201387e15f85344669487dbfe25c0f7f6682a8703249c5010417b590), but coverage numbers are still very low.

Am I doing something wrong?

**Comment by szhorvat** [comment]
P.S. This is in preparation for applying for the integration rewards. igraph now has a fiscal sponsor which finally allows the project to receive the report. Our situation is a bit unusual in that there's not a single PR we can present as evidence. Instead, the work was spread out over more than 3 years. Is there a contact person I can ask about how to best present the application in this situation?

**Comment by jonathanmetzman** [comment]
> I am new to ClusterFuzzLite, and only set up the integration yesterday (while we've been using OSS-Fuzz for a couple of years now). Perhaps I did something wrong.
> 
> These are our projects configurations:
> 
> * ClusterFuzzLite: https://github.com/igraph/igraph/tree/master/.clusterfuzzlite
> * OSS-Fuzz: https://github.com/google/oss-fuzz/tree/master/projects/igraph
> 
> They have the same exclusion rules. But the values I see in the ClusterFuzzLite report don't seem to respect the exclusions, and the excluded directories still show up:
> 
> https://igraph.github.io/clusterfuzz-storage-repo/coverage/latest/report/linux/report.html
> 
> In comparison, line coverage reported by OSS-Fuzz is 58%.
> 
> These are our GitHub Actions workflows (just set up yesterday): https://github.com/igraph/igraph/tree/master/.github/workflows I ran [cflite_cron.yml](https://github.com/igraph/igraph/blob/master/.github/workflows/cflite_cron.yml) manually just a few minutes ago, hoping that it'd update coverage reports based on the newly added exclusion rules. And it did indeed [push an update](https://github.com/igraph/clusterfuzz-storage-repo/commit/01efd8bd2052a9223a569da0de08279f51872bee#diff-3812aad2201387e15f85344669487dbfe25c0f7f6682a8703249c5010417b590), but coverage numbers are still very low.
> 
> Am I doing something wrong?

I think if you just set up cifuzz https://google.github.io/oss-fuzz/getting-started/continuous-integration/ it's enough for the reward. The full clusterfuzzlite integration is for non-users of oss-fuzz.

**Comment by szhorvat** [comment]
Oops, it seems I misunderstood. It did seem rather redundant given that we're already using OSS-Fuzz.

**Comment by jonathanmetzman** [comment]
Yup. But you should still use CIFuzz as it will get you your crashes faster

**Comment by szhorvat** [comment]
Does this look good? https://github.com/igraph/igraph/pull/2558

**Comment by jonathanmetzman** [comment]
I think so
