### ISSUE TITLE
Support gitlab CI

### ISSUE THREAD

**Issue by jonathanmetzman** [google/clusterfuzzlite#55]
Some people have expressed interest in using this with gitlab.
We should support it.

**Comment by jonathanmetzman** [comment]
One slight complication I noticed is that gitlab's CI doesn't have an API for uploading artifacts directly.
Instead it will upload artifacts left in a file path.

**Comment by jonathanmetzman** [comment]
Some users that might be interested:
1. Suricata
2. https://www.reddit.com/r/fuzzing/comments/qsb78d/clusterfuzzlite_continuous_fuzzing_for_all/

**Comment by CarpeDiem-CarpeNoctem** [comment]
maybe download the artifacts from the last session and upload them through the file path defined in gitlab-ci.yml

**Comment by hickford** [comment]
Already fixed? https://google.github.io/clusterfuzzlite/running-clusterfuzzlite/gitlab/

**Comment by inferno-chromium** [comment]
Yes closing.
