### ISSUE TITLE
CFLite reports an issue that CIFuzz can't find

### ISSUE THREAD

**Issue by evverx** [google/clusterfuzzlite#62]
I'm not sure whether it's a CFLite issue or CIFuzz issue but somehow in https://github.com/evverx/elfutils/pull/35 CFLite was able to catch a heap-buffer-overflow in about 40s while at the same time in https://github.com/evverx/elfutils/pull/25 CIFuzz kept fuzzing practically the same code for about three minutes and found nothing. It would be great if they could produce the same results (in this particular case the heap-buffer-overflow should have been found by CIFuzz)

**Comment by evverx** [comment]
Looks like CIFuzz found the issue but it wasn't reported because it's reproducible with the latest build. My bad. Closing. Sorry!

**Comment by jonathanmetzman** [comment]
> Looks like CIFuzz found the issue but it wasn't reported because it's reproducible with the latest build. My bad. Closing. Sorry!

Nothing to worry about!
Thanks as always for using our tools and for reporting issues when you notice them.
