### ISSUE TITLE
assumptions about CFLite runtime environment

### ISSUE THREAD

**Issue by evverx** [google/clusterfuzzlite#64]
According to https://google.github.io/clusterfuzzlite/build-integration/#fuzzer-execution-environment
> You should not make any assumptions on the availability of dependent packages in the execution environment and the built fuzzers should have dependencies statically linked.

I understand why fuzz targets integrated into OSS-Fuzz should be written that way but I'm not sure why CFLite should follow suit. If this restriction was lifted I think I could in theory use CFLite (in combination with OSS-Fuzz and CIFuzz) to build systemd fuzz targets linked dynamically against its dependencies and run them on GitHub. Those two modes are already kind of supported by the systemd build system but only one of them is used regularly on OSS-Fuzz.

**Comment by jonathanmetzman** [comment]
> According to https://google.github.io/clusterfuzzlite/build-integration/#fuzzer-execution-environment
> 
> > You should not make any assumptions on the availability of dependent packages in the execution environment and the built fuzzers should have dependencies statically linked.
> 
> I understand why fuzz targets integrated into OSS-Fuzz should be written that way but I'm not sure why CFLite should follow suit. 

I definitely understand this and ideally I would like to get rid of this restriction.
But I think it is going to be easier to maintain if we only support the single mode of running fuzzers across CIFuzz and ClusterFuzzLite users.
The maintenance burden is why this restriction remains.

**Comment by evverx** [comment]
> I think it is going to be easier to maintain 

Agreed.

But unfortunately at least systemd can't be linked against some of its dependencies statically, which in turn, prevents it from being fuzzed thoroughly. Basically I have to throw away fuzz targets I use to review PRs like https://github.com/systemd/systemd/pull/21454#issuecomment-981811887 because they can't be integrated into the CI.

**Comment by evverx** [comment]
On second thought I think it isn't worth it after all. I think there are easier ways to more or less achieve that using just public OSS-Fuzz corpora of the dependencies that can't be linked dynamically. Thanks!
