### ISSUE TITLE
There doesn't seem to be a way to minimize crashes

### ISSUE THREAD

**Issue by evverx** [google/clusterfuzzlite#72]
I think ideally files triggering new issues should be added to regression testsuites and to make it a bit easier I think it would be great if CFLite could minimize them. For example, in https://github.com/evverx/elfutils/actions/runs/1660223230 the file is kind of huge (15221 bytes) considering that the same issue can be triggered with just 196 bytes. Other than that it's usually much easier to track bugs down and fix them when files triggering them are as small as possible.

**Comment by jonathanmetzman** [comment]
How about a flag that asks CFL to minimize testcases found in PR fuzzing?
Note that I'm not sure it makes sense to do this in batch fuzzing because it will mess up the time we allocate to fuzzing, since in batch fuzzing we run other fuzzers after first crash is found, so minimizing the testcase will result in less time for other fuzzers.

**Comment by evverx** [comment]
> How about a flag that asks CFL to minimize testcases found in PR fuzzing?

I think something like `MINIMIZE_CRASHES: 1` should work. As far as I know unlike the "minimizer" used by OSS-Fuzz libFuzzer doesn't keep track of backtraces when `-minimize_crash=1` is passed to it so if it was used to implement that I think it would make sense to attach original and minimized crashes to make sure they actually triggered the same issue.

> Note that I'm not sure it makes sense to do this in batch fuzzing because it will mess up the time we allocate to fuzzing

I use OSS-Fuzz for batch fuzzing :-) but I agree that CFLite shouldn't try to minimize crashes in that mode (at least by default)

**Comment by evverx** [comment]
As far as I understand this issue can be closed. Thanks!
