### ISSUE TITLE
Is someone working on integrating this into Gitlab's CI?

### ISSUE THREAD

**Issue by 0xfede7c8** [google/clusterfuzzlite#73]
The title.

If not, this issue could be used to implement that change.

**Comment by jonathanmetzman** [comment]
Yes. You can track the progress here
<https://github.com/google/clusterfuzzlite/pull/70> and here
<https://github.com/google/oss-fuzz/pull/7073>.

**Comment by 0xfede7c8** [comment]
Thanks. Closing.

**Comment by catenacyber** [comment]
@0xfede7c8 you are welcome to test the current PR
