### ISSUE TITLE
CFlite artifacts are called "cifuzz-****"

### ISSUE THREAD

**Issue by evverx** [google/clusterfuzzlite#77]
I'm not sure how important this is but looking at https://github.com/evverx/libbpf/actions/runs/1728607427 it seems the artifacts should be called "cflite-***" instead. The only scenario I can imagine where it could break something is when both CFLite and CIFuzz are enabled at the same time though.

**Comment by oliverchang** [comment]
@jonathanmetzman thoughts? It doesn't seem too important to me, and enabling both at the same time doesn't make much sense AFAICT.

**Comment by evverx** [comment]
I think as long as CIFuzz is incompatible with forks due to https://github.com/google/oss-fuzz/issues/3731 it kind of makes sense to use both CIFuzz and CFLite. I don't think anyone does this in practice though.

**Comment by jonathanmetzman** [comment]
I think ideally we should use "clusterfuzzlite" rather than CIFuzz which isn't really the "brand" we are going to use moving forward.
I can change the name but it will break existing users. Better to do this sooner rather than later but I'm leaning towards not changing it.

**Comment by evverx** [comment]
There is another place where CFLite doesn't pop up even though I think it should. As far as I can tell there is no alternative to [the CIFUZZ environment variable](https://github.com/google/oss-fuzz/issues/4604) on CFLite.

**Comment by evverx** [comment]
I think there is exactly one project where both CIFuzz and CFLite are used and I'm pretty sure it can live with artifacts named like this :-) Closing.
