### ISSUE TITLE
jazzer_driver not available in local infra/helper.py run_fuzzer command

### ISSUE THREAD

**Issue by jtpereyda** [google/clusterfuzzlite#98]
I have a working cflite jvm demo here: https://github.com/jtpereyda/clusterfuzzlite-demo/tree/188fc3ccfcf51968c9a6961b9989341777c16ce0
With a working build that succesfully runs the fuzzer (finding an example exception): https://github.com/jtpereyda/clusterfuzzlite-demo/runs/6393527402?check_suite_focus=true

However, when I try the [recommended run_fuzzer command](https://github.com/google/clusterfuzzlite/blob/main/docs/build_integration.md#testing-locally):

```bash
python infra/helper.py run_fuzzer --external --corpus-dir=<path-to-temp-corpus-dir> $PATH_TO_PROJECT <fuzz_target>
```

I get a `/out/jazzer_driver: not found` error:

```
> python infra/helper.py run_fuzzer --external --corpus-dir $PATH_TO_PROJECT/inputs $PATH_TO_PROJECT ExampleFuzzer
INFO:root:Running: docker run --rm --privileged -i -e FUZZING_ENGINE=libfuzzer -e SANITIZER=address -e RUN_FUZZER_MODE=interactive -v /path/to/cfl-demo/inputs:/tmp/ExampleFuzzer_corpus -v /path/to/oss-fuzz/build/out/cfl-demo:/out -t gcr.io/oss-fuzz-base/base-runner run_fuzzer ExampleFuzzer.
rm: cannot remove '/tmp/ExampleFuzzer_corpus': Device or resource busy
/out/ExampleFuzzer -rss_limit_mb=2560 -timeout=25 /tmp/ExampleFuzzer_corpus < /dev/null
/out/ExampleFuzzer: 4: /out/jazzer_driver: not found
```

This led me on a goose chase trying to fix the local run before enabling the Github action and seeing that it was actually working. Still, it'd be super helpful to be able to test locally. I take it something on the server side is including the `jazzer_driver` executable, but that something is missing from the local `run_fuzzer` command.

**Comment by jonathanmetzman** [comment]
Ouch sorry about this. Let me try to fix this.

**Comment by jonathanmetzman** [comment]
I have a fix ready

**Comment by jtpereyda** [comment]
Thank you @jonathanmetzman ! That PR worked perfectly for me after running build_fuzzer and then run_fuzzer again.

**Comment by jonathanmetzman** [comment]
Np! Feel free to reach out (here or by email metzman at google.com) if you need any help or support with ClusterFuzzLite. We're more than happy to help!

**Comment by jtpereyda** [comment]
Thank you!
